### ISSUE TITLE
feat: penalty toggle

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/dueltasks#108]
### todo
- [x] Look why jobs failing in prod
  - [x]   Add D_U in env for worker service 20241025190042
- [x] test stripe works 
- [x] #114
- [ ] #116
- [x] #120
- [x] #119
- [x] #123

### related
b1c1bdc

**Comment by adnjoo** [comment]
check back later stripe dashboard see if user charged

<img width="542" alt="Screenshot 2024-10-25 at 9 48 36 AM" src="https://github.com/user-attachments/assets/7ff053a0-e213-4020-afb0-263e3b38507f">
