### ISSUE TITLE
pfp - Image upload

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/dueltasks#124]
### Prereqs
- #126

### Notes
- [Rails Active Storage Guide](https://edgeguides.rubyonrails.org/active_storage_overview.html)
- Configure AWS S3 as the storage backend for profile picture uploads.

---

### Tasks

- [x] **Set up AWS S3**
  - [x] Create an S3 bucket (e.g., `yourapp-profile-pictures`).
  - [x] Set bucket permissions for public access (or private with signed URLs if preferred).
  - [x] Add necessary IAM permissions for Active Storage to access the bucket.

- [x] **Configure Rails to use AWS S3**
  - [x] Add the `aws-sdk-s3` gem to `Gemfile`:
    ```ruby
    gem 'aws-sdk-s3', '~> 1.0'
    ```
  - [x] Set up Active Storage with S3 in `config/storage.yml`:
    ```yaml
    amazon:
      service: S3
      access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      region: us-east-1
      bucket: yourapp-profile-pictures
    ```
  - [x] Run `rails active_storage:install` and migrate the database.

- [x] **Add Profile Picture Upload to User Model**
  - [x] Attach `has_one_attached :profile_picture` to `User` model.
    ```ruby
    class User < ApplicationRecord
      has_one_attached :profile_picture
    end
    ```

- [x] **Set Up Profile Picture Upload Form**
  - [x] Add a file input in the form view:
    ```erb
    <%= form_with(model: @user, local: true) do |form| %>
      <%= form.file_field :profile_picture %>
      <%= form.submit %>
    <% end %>
    ```
  - [x] image limit e.g. 500kb

- [x] **Display Profile Picture**
  - [x] Use `url_for` helper to display the uploaded profile picture:
    ```erb
    <% if @user.profile_picture.attached? %>
      <%= image_tag url_for(@user.profile_picture) %>
    <% end %>
    ```
