### ISSUE TITLE
feat: pay to platform if user doesn't complete task

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/dueltasks#96]
### todo
- [x] **Add Deadline to Notes**
  - [x] #99
  - [x] Update `Note` model to schedule penalty check after saving with a deadline
- [x] **Create PenaltyJob for Handling Penalty Payments** #100
  - [x] Generate a Sidekiq PenaltyJob to handle the penalty payment process
- [x] **Charge User A via Stripe**
  - [x] Add `charge_user` method to handle penalty payments
- [x] **Schedule Penalty Check After Note is Saved**
  - [x] In the `Note` model, schedule the `PenaltyWorker` to run after the deadline
- [x] **Test the Payment Flow (test)** 
  - [x] Set up Stripe test credentials
  - [x] Simulate users with incomplete tasks and ensure the payment is processed (test)
  - [x] Check Stripe dashboard for successful payment records
- [ ] **Test the Payment Flow (real money)**
  - [x] Set up Stripe test credentials
  - [ ] Simulate users with incomplete tasks and ensure the payment is processed (test)
  - [ ] Check Stripe dashboard for successful payment records
- [ ] **Optional: Handle Payment Errors**
  - [ ] Add error handling in `charge_user` method for potential issues (e.g., card errors)
    ```ruby
    rescue Stripe::CardError => e
      Rails.logger.error "Stripe Error: #{e.message}"
    ```
- [ ] **Deploy and Monitor**
  - [ ] Deploy the changes to your production environment
  - [ ] Monitor for any issues or failed payments using Sidekiq logs and Stripe dashboard
