### ISSUE TITLE
sidekiq

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/dueltasks#97]
### Todo
- [x] test local
- [x] deploy to railway
  - [x] add Redis on railway
  - [x] add initializer
- [x] test deployed test job

```bash
[87e7e512-cff7-4c39-a278-1b66281c3c9d] RedisClient::CannotConnectError (Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379)):

[87e7e512-cff7-4c39-a278-1b66281c3c9d] 

Causes:

[87e7e512-cff7-4c39-a278-1b66281c3c9d] Errno::ECONNREFUSED (Connection refused - connect(2) for 127.0.0.1:6379)

[87e7e512-cff7-4c39-a278-1b66281c3c9d]   
```

```bash
#<LogTestJob:0x000000011fb81b20
 @_halted_callback_hook_called=nil,
 @arguments=[],
 @exception_executions={},
 @executions=0,
 @job_id="845df244-2388-4802-b498-cac0c18873d0",
 @priority=nil,
 @provider_job_id="d72ec476b71c712bcc77892d",
 @queue_name="default",
 @scheduled_at=nil,
 @successfully_enqueued=true,
 @timezone="UTC">
myapp(prod)> 
myapp(prod)> 
^C
myapp(prod)> 
```

**Comment by adnjoo** [comment]
Steps to Test Locally with Foreman
